version: '3'

services:
  web:
    env_file:
      - .env.prod
    command: gunicorn -c gunicorn.conf.py secret_notes.wsgi

  celery:
    env_file:
      - .env.prod

  db:
    env_file:
      - .env.prod
