# Generated by Django 3.1.7 on 2021-03-22 19:06

from django.db import migrations, models

import notes.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=notes.models.generate_slug, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('password', models.CharField(blank=True, max_length=80, null=True)),
                ('allowed_reads', models.IntegerField(default=0)),
                ('times_read', models.IntegerField(default=0)),
                ('notify_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_confirmation', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
