# Generated by Django 3.2.3 on 2021-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='allowed_reads',
            field=models.IntegerField(default=1),
        ),
    ]
