# Generated by Django 3.2.3 on 2021-05-21 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0002_alter_note_allowed_reads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notify_email',
        ),
    ]
