# Generated by Django 4.0 on 2021-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0003_remove_note_notify_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='password',
        ),
        migrations.AddField(
            model_name='note',
            name='salt',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
